### ISSUE TITLE
um, how do i playXD

### ISSUE THREAD

**Issue by robocart9** [Wolvan/MLP-Dating-Sim#1]
i dont know how to play the game, or is the game not uploaded ?
can i pls have help XD

**Comment by Wolvan** [comment]
The game was never finished, I mean, it kinda works and there are sample dialogue files, but it is definitely nothing that anyone would consider a game right now

**Comment by robocart9** [comment]
is there a way to play it tho, do i have to download something in particular? And why was it stopped?

**Comment by Wolvan** [comment]
If you download Love2D (0.9.2 I think, check the ./src/game/config.lua file for the correct version) and then run the game with the console command `love src/game` it should start up.

There really isn't anything to play, we have 2 mapped out test paths of around 3 screens but that is it. You can make your own by creating dialogue files like we have them in the src/game/resources folder

**Comment by Wolvan** [comment]
As to why the project was stopped? The team broke apart. Writers and artists stopped caring for it

**Comment by robocart9** [comment]
well, any thoughts about re-opening this story up if you get more people into making it? You dont see this kind of thing alot on the internet when it comes to mlp, so I think people would love the game even if it isnt that great, if your not, I understand, as it seems as if it has been a long time since this has stopped. On other terms, I wish you luck on whatever your doing now, and i hope you have a nice day!

**Comment by Wolvan** [comment]
The base is entirely ready. Heck, if you are a writer, you can just fork the repo, and some dialogue and asset files and PR it back into here. This project isn't exactly dead but I have no writers or artists and I am neither of those. So I kinda can't really do anything. The base is completely operational

**Comment by robocart9** [comment]
ok, so, i only really only got me, but im a writer [not in code tho, but plannin on going to college for that] and i have even written a story on fimfiction, tho i have writers block on that one, i dont know where to go from the point i put myself in, but i might be able to contact some artists.

**Comment by Wolvan** [comment]
You can rebuild the story from the ground up if you really wanted to. The dialogue files are extremely simple and should be easy to read for a non-coder as well. As I said, feel free to check out how they are structured
https://github.com/Wolvan/MLP-Dating-Sim/blob/master/src/game/resources/dialogues/aj_2a.mlpdsDialogue

About the artists? Really, it's up to you. If you want to continue this thing, feel free to and I can contribute the occassional engine patches. Feel free to open issues to discuss topics or art or anything you like, I give you free reign here basically

**Comment by robocart9** [comment]
ok, thanks, ill try to get this back up and running, and since you'll be contributing as well, ill make sure to let people know that you had a part in it, even if you decided not too, since you started it ill still give you credit. so, what did you use to build it in btw? was it the love2d thing?

**Comment by Wolvan** [comment]
love2d allows you to run it, yes

**Comment by robocart9** [comment]
k, and where do i get that?

**Comment by Wolvan** [comment]
http://bfy.tw/DXRa

**Comment by robocart9** [comment]
thanks, although i did just see how small your work was, and i see what you mean about it being very small XD, if you want, we can work together if your still interested in making this game/visual novel.

**Comment by robocart9** [comment]
nvm, i might wait to continue this when I know coding, cause it looks like to continue this game im gonna need to know some of the basics at least.

**Comment by robocart9** [comment]
anyway, good luck on whatever your working on or doing now! and have a nice day!
